kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: kudos-events-topic
  labels:
    strimzi.io/cluster: kafka-cluster
  namespace: jee-cloud
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
